name: SSL Certificate Expiry Date Check
description: "Check the validity of a SSL certificate for a given hostname"
author: Krzysztof Kowalczyk
inputs: 
  certificate-hostname: 
    description: "The hostname of that will be checked for a valid SSL certificate"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "alert-triangle"
  color: "yellow"